library(xlsx)
setwd("E:/COVID-19¹ş·ğÊı¾İ·ÖÎö")
data1 <- read.xlsx("hw1.xlsx",sheetIndex = 1)
data2 <- subset(data1,index!="NA")
cov(data2)
cor(data2,method = "spearman")
library(ggplot2)
plot1 <- ggplot(data2,aes(x=newcases,y=index)) + geom_point(shape=19) + xlab("new cases") + ylab("stockindex")+ ggtitle("newcases~stockindex")
plot2 <- ggplot(data2,aes(x=deaths,y=index)) + geom_point(shape=19) + xlab("deaths") + ylab("stockindex")+ ggtitle("deathincrease~stockindex")
plot3 <- ggplot(data2,aes(x=cumulativecases,y=index)) + geom_point(shape=19) + xlab("cumulative cases") + ylab("stockindex")+ ggtitle("cumulative~stockindex")
